const voyages = [
  {
    id: 1,
    destination: "Paris",
    continent: "Europe",
    typeVol: "Aller-retour",
    classe: "Business",
    prix: 3200,
    evaluation: 5,
    hotel: true,
    petitDejeuner: true,
    reduction: true,
    picture: "../images/pictures/Paris.jpg"
  },
  {
    id: 2,
    destination: "Tokyo",
    continent: "Asie",
    typeVol: "Aller simple",
    classe: "Économique",
    prix: 5400,
    evaluation: 4,
    hotel: true,
    petitDejeuner: false,
    reduction: false,
    picture: "../images/pictures/Tokyo.jpg"
  },
  {
    id: 3,
    destination: "Dubai",
    continent: "Asie",
    typeVol: "Aller-retour",
    classe: "Première classe",
    prix: 8600,
    evaluation: 5,
    hotel: true,
    petitDejeuner: true,
    reduction: true,
    picture: "../images/pictures/Dubai.jpg"
  },
  {
    id: 4,
    destination: "Rome",
    continent: "Europe",
    typeVol: "Multi-destinations",
    classe: "Économique",
    prix: 2800,
    evaluation: 3,
    hotel: false,
    petitDejeuner: false,
    reduction: false,
    picture: "../images/pictures/Rome.jpg"
  },
  {
    id: 5,
    destination: "Marrakech",
    continent: "Afrique",
    typeVol: "Aller-retour",
    classe: "Business",
    prix: 1900,
    evaluation: 4,
    hotel: true,
    petitDejeuner: true,
    reduction: true,
    picture: "../images/pictures/Marrakech.jpg"
  },
  {
    id: 6,
    destination: "New York",
    continent: "Amérique",
    typeVol: "Aller simple",
    classe: "Business",
    prix: 7200,
    evaluation: 5,
    hotel: true,
    petitDejeuner: false,
    reduction: false,
    picture: "../images/pictures/New.jpg"
  },
  {
    id: 7,
    destination: "Sydney",
    continent: "Océanie",
    typeVol: "Aller-retour",
    classe: "Économique",
    prix: 9100,
    evaluation: 4,
    hotel: false,
    petitDejeuner: false,
    reduction: true,
    picture: "../images/pictures/Sydney.jpg"
  },
  {
    id: 8,
    destination: "Bangkok",
    continent: "Asie",
    typeVol: "Aller-retour",
    classe: "Économique",
    prix: 3500,
    evaluation: 4,
    hotel: true,
    petitDejeuner: true,
    reduction: true,
    picture: "../images/pictures/Bangkok.jpg"
  },
  {
    id: 9,
    destination: "Londres",
    continent: "Europe",
    typeVol: "Aller simple",
    classe: "Business",
    prix: 4100,
    evaluation: 5,
    hotel: true,
    petitDejeuner: true,
    reduction: false,
    picture: "../images/pictures/London.jpg"
  },
  {
    id: 10,
    destination: "Istanbul",
    continent: "Asie",
    typeVol: "Aller-retour",
    classe: "Économique",
    prix: 2600,
    evaluation: 4,
    hotel: true,
    petitDejeuner: false,
    reduction: true,
    picture: "../images/pictures/Istanbul.jpg"
  },
  {
    id: 11,
    destination: "Barcelone",
    continent: "Europe",
    typeVol: "Aller-retour",
    classe: "Business",
    prix: 3700,
    evaluation: 5,
    hotel: true,
    petitDejeuner: true,
    reduction: true,
    picture: "../images/pictures/Barcelona.jpg"
  },
  {
    id: 12,
    destination: "Le Caire",
    continent: "Afrique",
    typeVol: "Aller simple",
    classe: "Économique",
    prix: 1800,
    evaluation: 3,
    hotel: false,
    petitDejeuner: false,
    reduction: false,
    picture: "../images/pictures/Cairo.jpg"
  },
  {
    id: 13,
    destination: "Rio",
    continent: "Amérique",
    typeVol: "Aller-retour",
    classe: "Business",
    prix: 6900,
    evaluation: 4,
    hotel: true,
    petitDejeuner: true,
    reduction: true,
    picture: "../images/pictures/Rio.jpg"
  },
  {
    id: 14,
    destination: "Séoul",
    continent: "Asie",
    typeVol: "Multi-destinations",
    classe: "Première classe",
    prix: 9900,
    evaluation: 5,
    hotel: true,
    petitDejeuner: true,
    reduction: false,
    picture: "../images/pictures/Seoul.jpg"
  },
  {
    id: 15,
    destination: "Athènes",
    continent: "Europe",
    typeVol: "Aller-retour",
    classe: "Économique",
    prix: 2400,
    evaluation: 4,
    hotel: false,
    petitDejeuner: false,
    reduction: true,
    picture: "../images/pictures/Athens.jpg"
  },
  {
    id: 16,
    destination: "Berlin",
    continent: "Europe",
    typeVol: "Aller simple",
    classe: "Business",
    prix: 3300,
    evaluation: 5,
    hotel: true,
    petitDejeuner: false,
    reduction: true,
    picture: "../images/pictures/Berlin.jpg"
  },
  {
    id: 17,
    destination: "Pékin",
    continent: "Asie",
    typeVol: "Aller-retour",
    classe: "Première classe",
    prix: 8700,
    evaluation: 5,
    hotel: true,
    petitDejeuner: true,
    reduction: false,
    picture: "../images/pictures/Beijing.jpg"
  },
  {
    id: 18,
    destination: "Toronto",
    continent: "Amérique",
    typeVol: "Aller simple",
    classe: "Économique",
    prix: 4900,
    evaluation: 4,
    hotel: false,
    petitDejeuner: false,
    reduction: true,
    picture: "../images/pictures/Toronto.jpg"
  },
  {
    id: 19,
    destination: "Doha",
    continent: "Asie",
    typeVol: "Aller-retour",
    classe: "Business",
    prix: 6400,
    evaluation: 5,
    hotel: true,
    petitDejeuner: true,
    reduction: true,
    picture: "../images/pictures/Doha.jpg"
  },
  {
    id: 20,
    destination: "Lisbonne",
    continent: "Europe",
    typeVol: "Aller simple",
    classe: "Économique",
    prix: 2100,
    evaluation: 4,
    hotel: true,
    petitDejeuner: false,
    reduction: true,
    picture: "../images/pictures/Lisbon.jpg"
  },
  {
    id: 21,
    destination: "Mexico",
    continent: "Amérique",
    typeVol: "Aller-retour",
    classe: "Business",
    prix: 6200,
    evaluation: 4,
    hotel: true,
    petitDejeuner: true,
    reduction: false,
    picture: "../images/pictures/Mexico.jpg"
  },
  {
    id: 22,
    destination: "Cape Town",
    continent: "Afrique",
    typeVol: "Aller simple",
    classe: "Économique",
    prix: 3100,
    evaluation: 5,
    hotel: false,
    petitDejeuner: false,
    reduction: true,
    picture: "../images/pictures/Cape.jpg"
  },
  {
    id: 23,
    destination: "Mumbai",
    continent: "Asie",
    typeVol: "Aller-retour",
    classe: "Business",
    prix: 4500,
    evaluation: 4,
    hotel: true,
    petitDejeuner: true,
    reduction: true,
    picture: "../images/pictures/Mumbai.jpg"
  },
  {
    id: 24,
    destination: "Amsterdam",
    continent: "Europe",
    typeVol: "Aller simple",
    classe: "Business",
    prix: 3800,
    evaluation: 5,
    hotel: true,
    petitDejeuner: false,
    reduction: false,
    picture: "../images/pictures/Amsterdam.jpg"
  },
  {
    id: 25,
    destination: "Los Angeles",
    continent: "Amérique",
    typeVol: "Multi-destinations",
    classe: "Première classe",
    prix: 10400,
    evaluation: 5,
    hotel: true,
    petitDejeuner: true,
    reduction: true,
    picture: "../images/pictures/Los.jpg"
  },
  {
    id: 26,
    destination: "Casablanca",
    continent: "Afrique",
    typeVol: "Aller-retour",
    classe: "Économique",
    prix: 1500,
    evaluation: 3,
    hotel: false,
    petitDejeuner: false,
    reduction: true,
    picture: "../images/pictures/Casablanca.jpg"
  },
  {
    id: 27,
    destination: "Singapour",
    continent: "Asie",
    typeVol: "Aller simple",
    classe: "Business",
    prix: 7600,
    evaluation: 5,
    hotel: true,
    petitDejeuner: true,
    reduction: false,
    picture: "../images/pictures/Singapore.jpg"
  },
  {
    id: 28,
    destination: "Prague",
    continent: "Europe",
    typeVol: "Aller-retour",
    classe: "Économique",
    prix: 2700,
    evaluation: 4,
    hotel: true,
    petitDejeuner: false,
    reduction: true,
    picture: "../images/pictures/Prague.jpg"
  },
  {
    id: 29,
    destination: "Buenos Aires",
    continent: "Amérique",
    typeVol: "Aller-retour",
    classe: "Business",
    prix: 6800,
    evaluation: 5,
    hotel: true,
    petitDejeuner: true,
    reduction: true,
    picture: "../images/pictures/Buenos.jpg"
  },
  {
    id: 30,
    destination: "Bali",
    continent: "Asie",
    typeVol: "Aller simple",
    classe: "Économique",
    prix: 4300,
    evaluation: 5,
    hotel: true,
    petitDejeuner: true,
    reduction: true,
    picture: "../images/pictures/Bali.jpg"
  }
];

localStorage.setItem('voyages', JSON.stringify(voyages));
const dataAvis = JSON.parse(localStorage.getItem("avisdata"))
