const voyages = [
  {
    id: 1,
    destination: "Paris",
    continent: "Europe",
    typeVol: "Aller-retour",
    classe: "Business",
    prix: 3200,
    evaluation: 5,
    hotel: true,
    petitDejeuner: true,
    reduction: true,
    picture: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800"
  },
  {
    id: 2,
    destination: "Tokyo",
    continent: "Asie",
    typeVol: "Aller simple",
    classe: "Économique",
    prix: 5400,
    evaluation: 4,
    hotel: true,
    petitDejeuner: false,
    reduction: false,
    picture: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800"
  },
  {
    id: 3,
    destination: "Dubai",
    continent: "Asie",
    typeVol: "Aller-retour",
    classe: "Première classe",
    prix: 8600,
    evaluation: 5,
    hotel: true,
    petitDejeuner: true,
    reduction: true,
    picture: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800"
  },
  {
    id: 4,
    destination: "Rome",
    continent: "Europe",
    typeVol: "Multi-destinations",
    classe: "Économique",
    prix: 2800,
    evaluation: 3,
    hotel: false,
    petitDejeuner: false,
    reduction: false,
    picture: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800"
  },
  {
    id: 5,
    destination: "Marrakech",
    continent: "Afrique",
    typeVol: "Aller-retour",
    classe: "Business",
    prix: 1900,
    evaluation: 4,
    hotel: true,
    petitDejeuner: true,
    reduction: true,
    picture: "https://images.unsplash.com/photo-1597212618440-806262de4f6b?w=800"
  },
  {
    id: 6,
    destination: "New York",
    continent: "Amérique",
    typeVol: "Aller simple",
    classe: "Business",
    prix: 7200,
    evaluation: 5,
    hotel: true,
    petitDejeuner: false,
    reduction: false,
    picture: "https://images.unsplash.com/photo-1499092346589-b9b6be3e94b2?w=800"
  },
  {
    id: 7,
    destination: "Sydney",
    continent: "Océanie",
    typeVol: "Aller-retour",
    classe: "Économique",
    prix: 9100,
    evaluation: 4,
    hotel: false,
    petitDejeuner: false,
    reduction: true,
    picture: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800"
  },
  {
    id: 8,
    destination: "Bangkok",
    continent: "Asie",
    typeVol: "Aller-retour",
    classe: "Économique",
    prix: 3500,
    evaluation: 4,
    hotel: true,
    petitDejeuner: true,
    reduction: true,
    picture: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800"
  },
  {
    id: 9,
    destination: "Londres",
    continent: "Europe",
    typeVol: "Aller simple",
    classe: "Business",
    prix: 4100,
    evaluation: 5,
    hotel: true,
    petitDejeuner: true,
    reduction: false,
    picture: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800"
  },
  {
    id: 10,
    destination: "Istanbul",
    continent: "Asie",
    typeVol: "Aller-retour",
    classe: "Économique",
    prix: 2600,
    evaluation: 4,
    hotel: true,
    petitDejeuner: false,
    reduction: true,
    picture: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800"
  },
  {
    id: 11,
    destination: "Barcelone",
    continent: "Europe",
    typeVol: "Aller-retour",
    classe: "Business",
    prix: 3700,
    evaluation: 5,
    hotel: true,
    petitDejeuner: true,
    reduction: true,
    picture: "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800"
  },
  {
    id: 12,
    destination: "Le Caire",
    continent: "Afrique",
    typeVol: "Aller simple",
    classe: "Économique",
    prix: 1800,
    evaluation: 3,
    hotel: false,
    petitDejeuner: false,
    reduction: false,
    picture: "https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=800"
  },
  {
    id: 13,
    destination: "Rio",
    continent: "Amérique",
    typeVol: "Aller-retour",
    classe: "Business",
    prix: 6900,
    evaluation: 4,
    hotel: true,
    petitDejeuner: true,
    reduction: true,
    picture: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800"
  },
  {
    id: 14,
    destination: "Séoul",
    continent: "Asie",
    typeVol: "Multi-destinations",
    classe: "Première classe",
    prix: 9900,
    evaluation: 5,
    hotel: true,
    petitDejeuner: true,
    reduction: false,
    picture: "https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=800"
  },
  {
    id: 15,
    destination: "Athènes",
    continent: "Europe",
    typeVol: "Aller-retour",
    classe: "Économique",
    prix: 2400,
    evaluation: 4,
    hotel: false,
    petitDejeuner: false,
    reduction: true,
    picture: "https://images.unsplash.com/photo-1503152394-c571994fd383?w=800"
  },
  {
    id: 16,
    destination: "Berlin",
    continent: "Europe",
    typeVol: "Aller simple",
    classe: "Business",
    prix: 3300,
    evaluation: 5,
    hotel: true,
    petitDejeuner: false,
    reduction: true,
    picture: "https://images.unsplash.com/photo-1560969184-10fe8719e047?w=800"
  },
  {
    id: 17,
    destination: "Pékin",
    continent: "Asie",
    typeVol: "Aller-retour",
    classe: "Première classe",
    prix: 8700,
    evaluation: 5,
    hotel: true,
    petitDejeuner: true,
    reduction: false,
    picture: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800"
  },
  {
    id: 18,
    destination: "Toronto",
    continent: "Amérique",
    typeVol: "Aller simple",
    classe: "Économique",
    prix: 4900,
    evaluation: 4,
    hotel: false,
    petitDejeuner: false,
    reduction: true,
    picture: "https://images.unsplash.com/photo-1517090504586-fde19ea6066f?w=800"
  },
  {
    id: 19,
    destination: "Doha",
    continent: "Asie",
    typeVol: "Aller-retour",
    classe: "Business",
    prix: 6400,
    evaluation: 5,
    hotel: true,
    petitDejeuner: true,
    reduction: true,
    picture: "https://images.unsplash.com/photo-1578895101408-1a36b834405b?w=800"
  },
  {
    id: 20,
    destination: "Lisbonne",
    continent: "Europe",
    typeVol: "Aller simple",
    classe: "Économique",
    prix: 2100,
    evaluation: 4,
    hotel: true,
    petitDejeuner: false,
    reduction: true,
    picture: "https://images.unsplash.com/photo-1585208798174-6cedd86e019a?w=800"
  },
  {
    id: 21,
    destination: "Mexico",
    continent: "Amérique",
    typeVol: "Aller-retour",
    classe: "Business",
    prix: 6200,
    evaluation: 4,
    hotel: true,
    petitDejeuner: true,
    reduction: false,
    picture: "https://images.unsplash.com/photo-1512813195386-6cf811ad3542?w=800"
  },
  {
    id: 22,
    destination: "Cape Town",
    continent: "Afrique",
    typeVol: "Aller simple",
    classe: "Économique",
    prix: 3100,
    evaluation: 5,
    hotel: false,
    petitDejeuner: false,
    reduction: true,
    picture: "https://images.unsplash.com/photo-1576485375217-d6a95e34d043?w=800"
  },
  {
    id: 23,
    destination: "Mumbai",
    continent: "Asie",
    typeVol: "Aller-retour",
    classe: "Business",
    prix: 4500,
    evaluation: 4,
    hotel: true,
    petitDejeuner: true,
    reduction: true,
    picture: "https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?w=800"
  },
  {
    id: 24,
    destination: "Amsterdam",
    continent: "Europe",
    typeVol: "Aller simple",
    classe: "Business",
    prix: 3800,
    evaluation: 5,
    hotel: true,
    petitDejeuner: false,
    reduction: false,
    picture: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800"
  },
  {
    id: 25,
    destination: "Los Angeles",
    continent: "Amérique",
    typeVol: "Multi-destinations",
    classe: "Première classe",
    prix: 10400,
    evaluation: 5,
    hotel: true,
    petitDejeuner: true,
    reduction: true,
    picture: "https://images.unsplash.com/photo-1534190760961-74e8c1c5c3da?w=800"
  },
  {
    id: 26,
    destination: "Casablanca",
    continent: "Afrique",
    typeVol: "Aller-retour",
    classe: "Économique",
    prix: 1500,
    evaluation: 3,
    hotel: false,
    petitDejeuner: false,
    reduction: true,
    picture: "https://images.unsplash.com/photo-1577147443647-81856d5151af?w=800"
  },
  {
    id: 27,
    destination: "Singapour",
    continent: "Asie",
    typeVol: "Aller simple",
    classe: "Business",
    prix: 7600,
    evaluation: 5,
    hotel: true,
    petitDejeuner: true,
    reduction: false,
    picture: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800"
  },
  {
    id: 28,
    destination: "Prague",
    continent: "Europe",
    typeVol: "Aller-retour",
    classe: "Économique",
    prix: 2700,
    evaluation: 4,
    hotel: true,
    petitDejeuner: false,
    reduction: true,
    picture: "https://images.unsplash.com/photo-1541849546-216549ae216d?w=800"
  },
  {
    id: 29,
    destination: "Buenos Aires",
    continent: "Amérique",
    typeVol: "Aller-retour",
    classe: "Business",
    prix: 6800,
    evaluation: 5,
    hotel: true,
    petitDejeuner: true,
    reduction: true,
    picture: "https://images.unsplash.com/photo-1589909202802-8f4aadce1849?w=800"
  },
  {
    id: 30,
    destination: "Bali",
    continent: "Asie",
    typeVol: "Aller simple",
    classe: "Économique",
    prix: 4300,
    evaluation: 5,
    hotel: true,
    petitDejeuner: true,
    reduction: true,
    picture: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800"
  }
];
localStorage.setItem('voyages', JSON.stringify(voyages));
const dataAvis = JSON.parse(localStorage.getItem("avisdata"))
